<a href="https://colab.research.google.com/github/RedDawe/Reinforcement_Chess/blob/master/chessown.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install tensorflow-gpu
import tensorflow as tf
print(tf.__version__)
assert tf.executing_eagerly()
import numpy as np

1.15.0
False


In [0]:
e = 0

n = 1
q = 2
r = 3
b = 4
k = 5
p = 6

N = -1
Q = -2
R = -3
B = -4
K = -5
P = -6

board = [[r, k, b, q, n, b, k, r],
         [p, p, p, p, p, p, p, p],
         [e, e, e, e, e, e, e, e],
         [e, e, e, e, e, e, e, e],
         [e, e, e, e, e, e, e, e],
         [e, e, e, e, e, e, e, e],
         [P, P, P, P, P, P, P, P],
         [R, K, B, Q, N, B, K, R]
]

board = np.array(board)

print(board)

[[ 3  5  4  2  1  4  5  3]
 [ 6  6  6  6  6  6  6  6]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [-6 -6 -6 -6 -6 -6 -6 -6]
 [-3 -5 -4 -2 -1 -4 -5 -3]]
5


In [0]:
inputs = tf.keras.Input(shape=(8, 8, 1)) #change into softmax as encoding and relu

model = tf.keras.layers.BatchNormalization()(inputs)

for i in range(16):
  cell = tf.keras.layers.Conv2D(filters=8, kernel_size=[1, 1], activation='tanh', padding='same')(model)
  cell = tf.keras.layers.Conv2D(filters=4, kernel_size=[3, 3], activation='tanh', padding='same')(cell)
  cell = tf.keras.layers.BatchNormalization()(cell)
  model = tf.keras.layers.Concatenate()(list([model, cell]))

model = tf.keras.Model(inputs=inputs, outputs=model)



model.compile(optimizer='adam', loss='mean_squared_error')

In [0]:
def make_move(board):
  return model.predict(board)

In [0]:
def decide_move(board, logits):
  biggest_diff = 0
  piece = []
  to = []

  for i in range(8):
    for j in range(8):
      #if abs(board[i, j] - logits[i, j]) > biggest_diff:
      #if -(logits[i, j] - board[i, j]) > biggest_diff:
      if board[i, j] > 0:
        if logits[i, j] / board[i, j] > biggest diff:
          moves = get_possible_moves(board, [i, j])

          for move in moves:
            copy_board = np.copy(board)
            copy_board[move[0], move[1]] = board[i, j]
            copy_board[i, j] = e

            if not is_check(copy_board, n)
              piece = [i, j]
              to = [move[0], move[1]]

In [0]:
def is_check(board, piece):
for i in range(8):
  for j in range(8):
    if board[i, j] == piece:
      coordinates = [i, j]

check = False
for i in range(8):
  for j in range(8):
    if board[i, j] > 0 and not check:
      moves = get_possible_moves(board, [i, j])
      check = coordinates in moves

return check

In [0]:
def get_possible_moves(board, coordinates): #put together all moves that 'is_legal', are on the board and aren't taking your own pieces
  legal_moves = []
  for i in range(8):
    for j in range(8):
      if (board[coordinates[0], coordinates[1]] > 0 and board[i, j] <= 0) or (board[coordinates[0], coordinates[1]] < 0 and board[i, j] >= 0)
        if is_legal(board, coordinates, [i, j])
          legal_moves.append([i, j])

  return legal_moves

In [0]:
def is_legal(board, piece, move): #check if move is in a direction that the piece moves andif squares between start and finish are empty
  if board[piece[0], piece[1]] == n: #KINGS
    return abs(piece[0] - move[0]) <= 1 and abs(piece[1] - move[1]) <= 1:

  elif board[piece[0], piece[1]] == q: #QUEEN
    if abs(piece[0] - move[0]) == 0:
      if abs(piece[1] - move[1]) >= 2:
        return np.all(board[min([piece[1], move[1]])+1 : max([piece[1], move[1]])] == e)
      else:
        return True
    elif abs(piece[1] - move[1]) == 0:
      if abs(piece[0] - move[0]) >= 2:
        return np.all(board[min([piece[0], move[0]])+1 : max([piece[0], move[0]])] == e)
      else:
        return True
    elif abs(piece[0] - move[0]) == abs(piece[1] - move[1])
      empty = True
      for i in range(8):
        for j in range(8):
          if board[i, j] != e:
            empty = False
      return empty
    else:
      return False

  elif board[piece[0], piece[1]] == r: #ROOK
    if abs(piece[0] - move[0]) == 0:
      if abs(piece[1] - move[1]) >= 2:
        return np.all(board[min([piece[1], move[1]])+1 : max([piece[1], move[1]])] == e)
      else:
        return True
    elif abs(piece[1] - move[1]) == 0:
      if abs(piece[0] - move[0]) >= 2:
        return np.all(board[min([piece[0], move[0]])+1 : max([piece[0], move[0]])] == e)
      else:
        return True
    else:
      return False

  elif board[piece[0], piece[1]] == b: #BISHOP
    if abs(piece[0] - move[0]) == abs(piece[1] - move[1])
      empty = True
      for i in range(8):
        for j in range(8):
          if board[i, j] != e:
            empty = False
      return empty
    else:
      return False

  elif board[piece[0], piece[1]] == k: #KNIGHT
    return (abs(piece[0] - move[0]) == 2 and abs(piece[0] - move[0]) == 1) or (abs(piece[0] - move[0]) == 1 and abs(piece[0] - move[0]) == 2)

  elif board[piece[0], piece[1]] == p: #PAWN
    return abs(piece[0] - move[0]) == 1 and abs(piece[0] - move[0]) == 0

  else:
    print('u fucked up')

In [0]:
n_steps = 2000
games_to_play = 100

In [0]:
for i in range(n_steps):
  for j in range(games_to_play):